In [1]:
import openhgnn

In [2]:
from openhgnn import Experiment
experiment = Experiment(model='HMPNN', dataset='OAG_CS', task='ktn', 
                        gpu=-1, lr=0.0001, 
                        max_epoch=30, num_layers=4,
                        task_type='L1',source_type='paper',target_type='author',
                        in_dim=1169,hid_dim=128,out_dim=128,rel_dim=128,
                        batch_size=64, use_matching_loss=True,
                        matching_coeff=0.5
                        )

------------------------------------------------------------------------------
 Basic setup of this experiment: 
     model: HMPNN    
     dataset: OAG_CS   
     task: ktn. 
 This experiment has following parameters. You can use set_params to edit them.
 Use print(experiment) to print this information again.
------------------------------------------------------------------------------
batch_size: 64
dataset_name: OAG_CS
device: cpu
gpu: -1
hid_dim: 128
hpo_search_space: None
hpo_trials: 100
in_dim: 1169
load_from_pretrained: False
lr: 0.0001
matching_coeff: 0.5
max_epoch: 30
mini_batch_flag: True
model_name: HMPNN
num_layers: 4
optimizer: Adam
out_dim: 128
output_dir: ./openhgnn/output/HMPNN
patience: 1
rel_dim: 128
seed: 0
source_type: paper
target_type: author
task_type: L1
test_batch: 50
train_batch: 200
use_best_config: False
use_matching_loss: True



In [3]:
experiment.run()


10 Nov 13:50    INFO  [Config Info]	Model: HMPNN,	Task: ktn,	Dataset: OAG_CS


KTN_trainer
starting ktn task
Loading dataset oag_cs
initing hmpnn model


  0%|          | 0/30 [00:00<?, ?it/s]10 Nov 13:50    INFO  Epoch 0 | mini-batch training

  0%|                                                                                          | 0/2001 [00:00<?, ?it/s]/home/lacuna42/miniforge3/envs/t/lib/python3.11/site-packages/dgl/dataloading/dataloader.py:1149: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
10 Nov 13:50    INFO  loss: 10.7339
  0%|                                                                                          | 0/2001 [00:07<?, ?it/s]
10 Nov 13:50    INFO  Epoch 0 | Train Loss 10.7339


torch.Size([544244, 128])
tensor([0.1841], grad_fn=<AddBackward0>)


  3%|▎         | 1/30 [00:34<16:46, 34.70s/it]10 Nov 13:51    INFO  Epoch 1 | mini-batch training

  0%|                                                                                          | 0/2001 [00:07<?, ?it/s]
10 Nov 13:51    INFO  Epoch 1 | Train Loss 9.5687


torch.Size([544244, 128])
tensor([0.1698], grad_fn=<AddBackward0>)


  7%|▋         | 2/30 [01:09<16:10, 34.67s/it]10 Nov 13:51    INFO  Epoch 2 | mini-batch training

  0%|                                                                                          | 0/2001 [00:07<?, ?it/s]
10 Nov 13:52    INFO  Epoch 2 | Train Loss 8.0877


torch.Size([544244, 128])
tensor([0.1565], grad_fn=<AddBackward0>)


 10%|█         | 3/30 [01:43<15:35, 34.64s/it]10 Nov 13:52    INFO  Epoch 3 | mini-batch training

  0%|                                                                                          | 0/2001 [00:07<?, ?it/s]
10 Nov 13:52    INFO  Epoch 3 | Train Loss 8.1661


torch.Size([544244, 128])
tensor([0.1445], grad_fn=<AddBackward0>)


10 Nov 13:53    INFO  [Train Info] Early Stop!	Epoch:3
 10%|█         | 3/30 [02:18<20:46, 46.15s/it]
