In [1]:
import dgl
import torch as th

In [3]:
g.ndata['feat']

NameError: name 'g' is not defined

In [2]:
glist, dims = dgl.load_graphs("oag_cs.bin")
g = glist[0]

In [22]:

train_mask = g.nodes['paper'].data["train_mask"]
test_mask = g.nodes['paper'].data["test_mask"]
train_idx = th.nonzero(train_mask, as_tuple=False).squeeze()
test_idx = th.nonzero(test_mask, as_tuple=False).squeeze()

In [20]:
sampler = dgl.dataloading.NeighborSampler([1,1,1,1])

In [26]:
dataloader = dgl.dataloading.DataLoader(
    g, {'paper':train_idx}, sampler,
    batch_size=3096, shuffle=True, drop_last=False, num_workers=4)

In [24]:
a,b,c=next(iter(dataloader))

/home/lacuna42/miniforge3/envs/t/lib/python3.11/site-packages/dgl/dataloading/dataloader.py:1149: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(


In [27]:
len(dataloader)

42

In [ ]:
h=sg.ndata['feat']

In [ ]:
h

{'affiliation': tensor([[ 0.0006, -0.0005,  0.0020,  ..., -0.0009,  0.0008,  0.0547],
         [ 0.0012, -0.0009,  0.0037,  ..., -0.0010,  0.0005,  0.0366],
         [ 0.0025, -0.0016,  0.0014,  ..., -0.0009,  0.0009,  0.0476],
         ...,
         [ 0.0025, -0.0009,  0.0004,  ..., -0.0014,  0.0008,  0.0398],
         [ 0.0016,  0.0079,  0.0101,  ..., -0.0057,  0.0008,  0.0481],
         [ 0.0017, -0.0032, -0.0017,  ...,  0.0001,  0.0007,  0.0186]]),
 'author': tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.4300e-05,
          -1.9599e-03,  1.6473e-02],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.5311e-04,
          -1.8717e-03,  9.1673e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.0104e-04,
           8.5131e-04,  2.4105e-02],
         ...,
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.4732e-05,
           1.2805e-03,  2.4468e-02],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  9.7535e-04,
          -1.4246e-03,  9.9716e

In [ ]:
a['author'].shape

torch.Size([1221])

In [ ]:
import torch
def process_category(labels: torch.tensor, num_classes: int) -> torch.tensor:
    if labels.shape[1] != num_classes:
        processed_labels = torch.zeros((labels.shape[0], num_classes))
        num_indices = torch.count_nonzero(labels + 1, dim=1)
        for i in range(labels.shape[0]):
            indices = labels[i, : num_indices[i]].to(torch.int)
            processed_labels[i, indices] = 1 / num_indices[i].clamp(min=1)
    else:
        processed_labels = labels
    return processed_labels

{'affiliation': tensor([[ 0.0029, -0.0018,  0.0022,  ..., -0.0012,  0.0005,  0.0403],
         [ 0.0063,  0.0010,  0.0018,  ..., -0.0010,  0.0011,  0.0296],
         [ 0.0037,  0.0021,  0.0017,  ..., -0.0016,  0.0004,  0.0286],
         ...,
         [ 0.0008, -0.0025,  0.0030,  ..., -0.0001, -0.0033,  0.0099],
         [ 0.0025, -0.0022,  0.0038,  ...,  0.0043, -0.0015,  0.0042],
         [ 0.0029, -0.0014, -0.0007,  ...,  0.0044,  0.0012,  0.0136]]),
 'author': tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.7267e-05,
          -1.3538e-04,  5.7543e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3289e-03,
           9.0451e-04,  9.6308e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.7089e-04,
           3.0572e-03,  4.0321e-03],
         ...,
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00, -1.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00, -1.0000e

In [ ]:
lbl=c[0].ndata['L1']['paper']

In [ ]:
lbl = process_category(lbl, 275)

In [ ]:
lbl.size()

torch.Size([3027, 275])

In [ ]:
dataloader = torch.utils.data.DataLoader(
    train_idx,
    batch_size=64,
    collate_fn=source_sampler.sampler_subgraph,
    # num_workers=self.args.num_workers,
    shuffle=True,
    drop_last=False,
)

NameError: name 'source_sampler' is not defined

In [ ]:
a = next(iter(dataloader))

In [ ]:
a[0]

Graph(num_nodes={'affiliation': 3, 'author': 4, 'field': 4, 'paper': 68, 'venue': 4},
      num_edges={('affiliation', 'affiliation-author', 'author'): 4, ('author', 'author-affiliation', 'affiliation'): 4, ('author', 'author-paper', 'paper'): 4, ('field', 'field-field', 'field'): 0, ('field', 'field-paper', 'paper'): 12, ('paper', 'paper-author', 'author'): 4, ('paper', 'paper-field', 'field'): 12, ('paper', 'paper-paper', 'paper'): 4, ('paper', 'paper-venue', 'venue'): 6, ('venue', 'venue-paper', 'paper'): 6},
      metagraph=[('affiliation', 'author', 'affiliation-author'), ('author', 'affiliation', 'author-affiliation'), ('author', 'paper', 'author-paper'), ('paper', 'author', 'paper-author'), ('paper', 'field', 'paper-field'), ('paper', 'paper', 'paper-paper'), ('paper', 'venue', 'paper-venue'), ('field', 'field', 'field-field'), ('field', 'paper', 'field-paper'), ('venue', 'paper', 'venue-paper')])

In [ ]:
a[1]

{'paper': tensor([ 33651, 264064,  14129,  39863, 543680, 260598,   1306, 461042, 137527,
         294628, 374634, 439779, 517751, 286602, 418241,  67096, 245625, 411516,
         296457, 362784, 238363, 507455, 258262, 499626, 481229, 319118, 510740,
         230058, 402512, 372653,  83105, 398140, 538131, 137585, 295265, 198069,
         152263, 103080, 356339,  83636, 350655, 494942, 339255, 235273, 457007,
         287447,  33411, 263254, 379369,  84454, 343389, 278408, 343024, 406782,
         407633, 282809, 300775, 396011, 410717,  25376, 170043, 408125, 196552,
         126510, 259669, 264690, 350802, 170224]),
 'author': tensor([316872, 129736, 316873, 263227]),
 'field': tensor([11117, 28920, 26443,  6745]),
 'venue': tensor([6216, 4184, 3527, 4798]),
 'affiliation': tensor([ 903, 5136, 2587])}

In [ ]:
sg=a[0]

In [15]:
def optimized_process_category(labels: torch.tensor, num_classes: int) -> torch.tensor:
    if labels.shape[1] != num_classes:
        processed_labels = torch.zeros((labels.shape[0], num_classes), dtype=torch.float)
        valid_labels = labels >= 0
        num_indices = valid_labels.sum(dim=1)
        weights = (1.0 / num_indices.clamp(min=1).unsqueeze(1)).float()
        processed_labels.scatter_add_(1, labels * valid_labels, weights * valid_labels)
    else:
        processed_labels = labels.float()
    return processed_labels


In [16]:
labels = torch.tensor([[0,3,-1,-1,-1],[5,-1,-1,-1,-1]])
num_classes = 6

processed_labels = optimized_process_category(labels, num_classes)
print(processed_labels)

tensor([[0.5000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000]])


In [ ]:
lbl=

In [ ]:
# sampler = dgl.dataloading.MultiLayerFullNeighborSampler(4)
sampler = dgl.dataloading.NeighborSampler([4, 4, 4, 4])
dataloader = dgl.dataloading.DataLoader(
    g,
    {'paper':train_idx},
    sampler,
    batch_size=64,
    shuffle=True,
    drop_last=False,
    # num_workers=4,
)

In [ ]:
dataloader

In [ ]:
input_nodes, output_nodes, blocks = next(iter(dataloader))

/home/lacuna42/miniforge3/envs/t/lib/python3.11/site-packages/dgl/dataloading/dataloader.py:1149: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(


In [ ]:
for key, valud in input_nodes.items():
    print(key, valud.shape)

affiliation torch.Size([1456])
author torch.Size([27224])
field torch.Size([16016])
paper torch.Size([95813])
venue torch.Size([2276])


In [ ]:
input_nodes

{'affiliation': tensor([  12, 1162,  401,  ..., 1976, 8583, 2821]),
 'author': tensor([ 39272, 166534, 166535,  ..., 471093, 471095, 471096]),
 'field': tensor([19352, 10896, 34017,  ..., 40603, 12309, 27933]),
 'paper': tensor([ 64303, 428584, 254819,  ..., 466368, 535494, 323348]),
 'venue': tensor([ 562, 5285, 3053,  ..., 1862, 3666,  360])}

In [ ]:
g.ndata["feat"]

{'affiliation': tensor([[ 0.0029, -0.0018,  0.0022,  ..., -0.0012,  0.0005,  0.0403],
         [ 0.0063,  0.0010,  0.0018,  ..., -0.0010,  0.0011,  0.0296],
         [ 0.0037,  0.0021,  0.0017,  ..., -0.0016,  0.0004,  0.0286],
         ...,
         [ 0.0008, -0.0025,  0.0030,  ..., -0.0001, -0.0033,  0.0099],
         [ 0.0025, -0.0022,  0.0038,  ...,  0.0043, -0.0015,  0.0042],
         [ 0.0029, -0.0014, -0.0007,  ...,  0.0044,  0.0012,  0.0136]]),
 'author': tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.7267e-05,
          -1.3538e-04,  5.7543e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3289e-03,
           9.0451e-04,  9.6308e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.7089e-04,
           3.0572e-03,  4.0321e-03],
         ...,
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00, -1.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00, -1.0000e

In [ ]:
labels = g.ndata["L1"]["author"]

In [ ]:
lbl_dim = dims["L1"]

In [ ]:
processed_labels = {}
for task_type in ["L1"]:
    processed_labels[task_type] = {}
    for node_type in ["author"]:
        labels = g.ndata[task_type][node_type]
        if labels.shape[1] != dims[task_type]:
            processed_labels[task_type][node_type] = torch.zeros(
                (labels.shape[0], dims[task_type])
            )
            num_indices = torch.count_nonzero(labels + 1, dim=1)
            for i in range(labels.shape[0]):
                indices = labels[i, : num_indices[i]].to(torch.int)
                processed_labels[task_type][node_type][i, indices] = 1 / num_indices[
                    i
                ].clamp(min=1)
        else:
            processed_labels[task_type][node_type] = labels

RuntimeError: shape mismatch: value tensor of shape [510189, 275] cannot be broadcast to indexing result of shape [668109]

In [ ]:
def process_category(labels: torch.tensor, num_classes: int) -> torch.tensor:
    if labels.shape[1] != num_classes:
        processed_labels = torch.zeros((labels.shape[0], num_classes))
        num_indices = torch.count_nonzero(labels + 1, dim=1)
        for i in range(labels.shape[0]):
            indices = labels[i, : num_indices[i]].to(torch.int)
            processed_labels[i, indices] = 1 / num_indices[i].clamp(min=1)
    else:
        processed_labels = labels
    return processed_labels

In [ ]:
lb = g.ndata["L1"]["author"]

In [ ]:
num_indices

In [ ]:
a = process_category(lb[:50], dims["L1"].item())

In [ ]:
a

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [1.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])

In [ ]:
lb[42]

tensor([19., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1.])

In [ ]:
a[42][19]

tensor(1.)

In [ ]:
g.adj(etype='paper-author')


SparseMatrix(indices=tensor([[387067, 134013, 134013,  ..., 102817, 304115, 529407],
                             [     1,      1,      2,  ..., 510171, 392963, 510188]]),
             values=tensor([1., 1., 1.,  ..., 1., 1., 1.]),
             shape=(544244, 510189), nnz=1091559)

In [ ]:
import dgl.sparse

In [5]:
g.ndata['L1']

{'author': tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  0., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [27., 40., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]),
 'paper': tensor([[ 7., 13.,  4.,  ..., -1., -1., -1.],
         [40., -1., -1.,  ..., -1., -1., -1.],
         [ 7., 13.,  4.,  ..., -1., -1., -1.],
         ...,
         [ 9.,  4., 31.,  ..., -1., -1., -1.],
         [ 6., 20., -1.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]]),
 'venue': tensor([[19., 20.,  9.,  ..., -1., -1., -1.],
         [ 2.,  1., 18.,  ..., -1., -1., -1.],
         [46.,  1., 49.,  ..., -1., -1., -1.],
         ...,
         [ 3., 21., 20.,  ..., -1., -1., -1.],
         [ 7., 40., 10.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]])}

In [34]:
x=g.ndata['L1']['author']

In [36]:
import torch
y=torch.count_nonzero(x+1, dim=1)

In [37]:
y


tensor([0, 2, 0,  ..., 0, 2, 0])

In [38]:
max(y)

tensor(30)

In [26]:
z=(y==0)

In [27]:
z

tensor([ True, False,  True,  ...,  True, False,  True])

In [29]:
z.sum()/len(z)

tensor(0.5462)

In [5]:
import torch
new_label={}
for label_type in ['L1','L2']:
    label=g.ndata[label_type]
    new_label[label_type]={}
    for ntype in label.keys():
        x=label[ntype]
        y=torch.count_nonzero(x+1, dim=1)
        max_len=max(y)
        print(max_len)
        new_label[label_type][ntype]=x[:,:max_len]
        z=(y==0)
        print(f"{label_type} {ntype} {z.sum()} {len(z)} {z.sum()/len(z)}")

tensor(30)
L1 author 278663 510189 0.5461956262588501
tensor(7)
L1 paper 0 544244 0.0
tensor(50)
L1 venue 19 6934 0.0027401212137192488
tensor(50)
L2 author 283331 510189 0.5553451776504517
tensor(8)
L2 paper 16801 544244 0.03087034448981285
tensor(50)
L2 venue 74 6934 0.010672050528228283


In [11]:
for label_type in new_label.keys():
    g.ndata.pop(label_type)
    g.ndata[label_type]=new_label[label_type]

In [15]:
dgl.save_graphs("noag_cs.bin", [g], dims)

In [14]:
g.ndata['L1']['author'].shape

torch.Size([510189, 30])

In [42]:
l1=g.ndata.pop('L1')

In [43]:
l1

{'author': tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  0., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [27., 40., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]),
 'paper': tensor([[ 7., 13.,  4.,  ..., -1., -1., -1.],
         [40., -1., -1.,  ..., -1., -1., -1.],
         [ 7., 13.,  4.,  ..., -1., -1., -1.],
         ...,
         [ 9.,  4., 31.,  ..., -1., -1., -1.],
         [ 6., 20., -1.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]]),
 'venue': tensor([[19., 20.,  9.,  ..., -1., -1., -1.],
         [ 2.,  1., 18.,  ..., -1., -1., -1.],
         [46.,  1., 49.,  ..., -1., -1., -1.],
         ...,
         [ 3., 21., 20.,  ..., -1., -1., -1.],
         [ 7., 40., 10.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]])}

In [44]:
g.ndata.keys()

dict_keys(['feat', 'train_mask', 'val_mask', 'test_mask', 'L2', 'dists', 'venue'])

In [45]:
l1

{'author': tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  0., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [27., 40., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]),
 'paper': tensor([[ 7., 13.,  4.,  ..., -1., -1., -1.],
         [40., -1., -1.,  ..., -1., -1., -1.],
         [ 7., 13.,  4.,  ..., -1., -1., -1.],
         ...,
         [ 9.,  4., 31.,  ..., -1., -1., -1.],
         [ 6., 20., -1.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]]),
 'venue': tensor([[19., 20.,  9.,  ..., -1., -1., -1.],
         [ 2.,  1., 18.,  ..., -1., -1., -1.],
         [46.,  1., 49.,  ..., -1., -1., -1.],
         ...,
         [ 3., 21., 20.,  ..., -1., -1., -1.],
         [ 7., 40., 10.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]])}

In [46]:
l1_author=l1.pop('author')

In [47]:
l1_author

tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [ 1.,  0., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [27., 40., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [51]:
l1_author[:,:30]

tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [ 1.,  0., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [27., 40., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [52]:
nl1_author=l1_author[:,:30]

In [53]:
nl1_author.shape

torch.Size([510189, 30])

In [58]:
torch.argsort(nl1_author[:,-1],descending=True)

tensor([  4455, 340130, 340122,  ..., 170057, 170056, 170055])

In [59]:
l1_author[4455]

tensor([ 14., 111., 191.,  39.,  19., 134., 226., 119.,  44.,  36., 208.,  28.,
         29., 209.,  62., 159.,  10.,  16.,  23.,  31.,   4.,  53.,   2.,  61.,
         40.,  46.,  59.,  13.,  20.,   6.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.])

In [60]:
nl1_author[4455]

tensor([ 14., 111., 191.,  39.,  19., 134., 226., 119.,  44.,  36., 208.,  28.,
         29., 209.,  62., 159.,  10.,  16.,  23.,  31.,   4.,  53.,   2.,  61.,
         40.,  46.,  59.,  13.,  20.,   6.])

In [61]:
l1['author']=nl1_author

In [62]:
l1

{'paper': tensor([[ 7., 13.,  4.,  ..., -1., -1., -1.],
         [40., -1., -1.,  ..., -1., -1., -1.],
         [ 7., 13.,  4.,  ..., -1., -1., -1.],
         ...,
         [ 9.,  4., 31.,  ..., -1., -1., -1.],
         [ 6., 20., -1.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]]),
 'venue': tensor([[19., 20.,  9.,  ..., -1., -1., -1.],
         [ 2.,  1., 18.,  ..., -1., -1., -1.],
         [46.,  1., 49.,  ..., -1., -1., -1.],
         ...,
         [ 3., 21., 20.,  ..., -1., -1., -1.],
         [ 7., 40., 10.,  ..., -1., -1., -1.],
         [ 5., 89., -1.,  ..., -1., -1., -1.]]),
 'author': tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
         [ 1.,  0., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [27., 40., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]])}

In [63]:
l1_paper=l1.pop('paper')

In [64]:
l1_paper

tensor([[ 7., 13.,  4.,  ..., -1., -1., -1.],
        [40., -1., -1.,  ..., -1., -1., -1.],
        [ 7., 13.,  4.,  ..., -1., -1., -1.],
        ...,
        [ 9.,  4., 31.,  ..., -1., -1., -1.],
        [ 6., 20., -1.,  ..., -1., -1., -1.],
        [ 5., 89., -1.,  ..., -1., -1., -1.]])